AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Default: dev 

  SourceBucket:
    Type: String
  
  CognitoUserName:
    Type: String
  
  ThumbnailSize:
    Type: Number
    Default: 150

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "images-${AWS::StackName}-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
    
  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "thumbnails-${AWS::StackName}-${Environment}"

  ImageProcessingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ImageProcessingFunction-${AWS::StackName}-${Environment}"
      Handler: image_processor.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn 
      Code: 
        S3Bucket: !Ref SourceBucket
        S3Key: image_processor_1.1.zip
      Runtime: python3.13
      Timeout: 30
      Environment:
        Variables:
          IMAGES_BUCKET: !Ref ImagesBucket
          THUMBNAIL_BUCKET: !Ref ThumbnailBucket
      Layers: 
        - !Ref LayerUtilities
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "LambdaExecutionRole-${AWS::StackName}-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow 
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      
      Policies:
        - PolicyName: !Sub "LambdaS3AccessPolicy-${AWS::StackName}-${Environment}"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow 
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: 
                  - !Sub "arn:aws:s3:::images-${AWS::StackName}-${Environment}" 
                  - !Sub "arn:aws:s3:::images-${AWS::StackName}-${Environment}/*"
                  - !Sub "arn:aws:s3:::thumbnails-${AWS::StackName}-${Environment}"
                  - !Sub "arn:aws:s3:::thumbnails-${AWS::StackName}-${Environment}/*"

  ImageProcessingApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "ImageProcessingApi-${AWS::StackName}-${Environment}"
      ProtocolType: HTTP
      CorsConfiguration: 
        AllowMethods:
          - '*'
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With

  CloudWatchLogGroupApi:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/ImageProcessingApi-${AWS::StackName}-${Environment}"
      RetentionInDays: 14
    
  ImageProcessingApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ImageProcessingApi
      StageName: !Ref Environment
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt CloudWatchLogGroupApi.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'
  
  ImageProcessingApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties: 
      ApiId: !Ref ImageProcessingApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ImageProcessingFunction.Arn
      PayloadFormatVersion: '2.0'
      IntegrationMethod: POST

  ImageProcessingApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ImageProcessingApi
      RouteKey: 'POST /process'
      Target: !Sub 'integrations/${ImageProcessingApiIntegration}'
      AuthorizationType: JWT
      AuthorizerId: !Ref ImageProcessingApiAuthorizer
      
  LambdaApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ImageProcessingFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ImageProcessingApi}/*" 
    
  CognitoUserPool: 
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "ImageProcessingUserPool-${AWS::StackName}-${Environment}"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false 
      Schema: 
        - Name: email
          Required: true
          Mutable: true
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "ImageProcessingUserPoolClient-${AWS::StackName}-${Environment}"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
    
  CognitoUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Username: !Ref CognitoUserName
      DesiredDeliveryMediums: [] 
      MessageAction: SUPPRESS

  ImageProcessingApiAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref ImageProcessingApi
      AuthorizerType: JWT
      IdentitySource: 
        - "$request.header.Authorization"
      Name: CognitoAuthorizer
      JwtConfiguration:
        Audience:
          - !Ref CognitoUserPoolClient
        Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
  
  LayerUtilities: 
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "UtilitiesLayer-${Environment}"
      Description: "Layer for utility functions"
      Content:
        S3Bucket: !Ref SourceBucket
        S3Key: utilities_1.0.zip
      CompatibleRuntimes:
        - python3.13
